In [2]:
import numpy as np

In [ ]:
#Question 1

MyList = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
MyArray = np.array(MyList)
print(MyArray.ndim())
print(MyArray.shape)

In [12]:
#Question 2

NewArray = np.arange(20)
print(NewArray[10:16])

[10 11 12 13 14 15]


In [6]:
#Question 3

NewList = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30], [31, 32, 33, 34, 35]]
FirstArray = np.array(NewList)
SecondArray = np.array(NewList)
AddArray = np.add(FirstArray, SecondArray)
print(AddArray)
SubArray = np.subtract(FirstArray, SecondArray)
print(SubArray)
MultArray = np.multiply(FirstArray, SecondArray)
print(MultArray)
DivArray = np.divide(FirstArray, SecondArray)
print(DivArray)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]
 [62 64 66 68 70]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[   1    4    9   16   25]
 [  36   49   64   81  100]
 [ 121  144  169  196  225]
 [ 256  289  324  361  400]
 [ 441  484  529  576  625]
 [ 676  729  784  841  900]
 [ 961 1024 1089 1156 1225]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [8]:
#Question 4

FirstArray = np.array([1, 2, 3, 4, 5])
SecondArray = np.array([[1, 2], [3, 4]])

ResultArray = np.add(FirstArray, SecondArray)


ValueError: operands could not be broadcast together with shapes (5,) (2,2) 

In [15]:
#Question 5

FirstArray = np.array([1, 2, 3, 4, 5])
SecondArray = np.array([[10, 1], [20, 2], [30, 3], [40, 4], [50, 5]])

ResultArray = np.vstack(FirstArray)
print(ResultArray)

ResultArray = np.hstack(SecondArray)
print(ResultArray)

[[1]
 [2]
 [3]
 [4]
 [5]]
[10  1 20  2 30  3 40  4 50  5]


In [21]:
#Question 6
FirstArray = np.array([[1, 2], [3, 4],[5, 6]])
SecondArray = np.array([[10, 20], [30, 40], [50, 60]])

print(np.concatenate((FirstArray, SecondArray), axis=0))
print(np.concatenate((FirstArray, SecondArray), axis=1))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [10 20]
 [30 40]
 [50 60]]
[[ 1  2 10 20]
 [ 3  4 30 40]
 [ 5  6 50 60]]


In [3]:
import pandas as pd

In [30]:
#Question 7
MyList = [['1','Joe', 'M', 'Michigan'], ['2','Jack', 'M', 'Dallas'], ['3','Jill', 'F', 'California'], 
          ['4','Sam', 'M', 'Texas'], ['5','Peter', 'M', 'New York'], ['6','Kathy', 'F', 'San Fransico'], 
          ['7','Jim', 'M', 'Troy'], ['8','Colleen', 'F', 'Chicago']]
MyColumns = ['ID', 'Name', 'Sex', 'State']
MyDataFrame = pd.DataFrame(MyList, columns = MyColumns)
print(MyDataFrame)

  ID     Name Sex         State
0  1      Joe   M      Michigan
1  2     Jack   M        Dallas
2  3     Jill   F    California
3  4      Sam   M         Texas
4  5    Peter   M      New York
5  6    Kathy   F  San Fransico
6  7      Jim   M          Troy
7  8  Colleen   F       Chicago


In [4]:
# Question 8
MyDict = {"Name": ['Ken', 'Stone', 'Tim', 'Keith'],
          "Class":['I', 'II', 'I', 'III'],
          "Section": ['A', 'B', 'A', 'B'], 
          "Mark1": [90, 99, 95, 85], 
          "Mark2": [80, 75, 80, 75], 
          "Mark3": [95, 85, 98, 93], 
          "Mark4": [75, 95, 85, 80], 
          "Mark5": [85, 90, 95, 99]
          }
MyDataFrame = pd.DataFrame(MyDict)
print(MyDataFrame)

  Class  Mark1  Mark2  Mark3  Mark4  Mark5   Name Section
0     I     90     80     95     75     85    Ken       A
1    II     99     75     85     95     90  Stone       B
2     I     95     80     98     85     95    Tim       A
3   III     85     75     93     80     99  Keith       B


In [16]:
#Question 9
NewDataFrame = MyDataFrame.loc[[False, True, True, False]]
print(NewDataFrame)
IndexDataFrame = MyDataFrame.iloc[1:3]
print(IndexDataFrame)

  Class  Mark1  Mark2  Mark3  Mark4  Mark5   Name Section
1    II     99     75     85     95     90  Stone       B
2     I     95     80     98     85     95    Tim       A
  Class  Mark1  Mark2  Mark3  Mark4  Mark5   Name Section
1    II     99     75     85     95     90  Stone       B
2     I     95     80     98     85     95    Tim       A


In [29]:
#Question 10
import numpy as np
SampleDictionary = {

    'Name':['George','Andrea','Micheal','Maggie','Ravi','Xien','Jalpa',np.nan],
    'State':['Arizona','Georgia','New york','Indiana','Florida','California',np.nan,np.nan],
    'Gender':["M","F","M","F","M","M",np.nan,np.nan],
    'Score':[63,48,56,75,np.nan,77,np.nan,np.nan]
   }
OutputDataFrame = pd.DataFrame(SampleDictionary,columns=['Name','State','Gender','Score'])

# The following will print the number of not null columns for each column
print(OutputDataFrame.notnull().sum())

# The following will print the number of not null columns for each column using the count function and axis
print(OutputDataFrame.count(axis=0))

# The following will print the number of not null columns for each column using the apply function, lambda, count, axis
print(OutputDataFrame.apply(lambda x : x.count(), axis=0))

Name      7
State     6
Gender    6
Score     5
dtype: int64
Name      7
State     6
Gender    6
Score     5
dtype: int64
Name      7
State     6
Gender    6
Score     5
dtype: int64


In [41]:
# Question 11
MyDict = {"Name": ['Ken', 'Stone', 'Tim', 'Keith'],
          "Class":['I', 'II', 'I', 'III'],
          "Section": ['A', 'B', 'A', 'B'], 
          "Mark1": [90, np.nan, 95, 85], 
          "Mark2": [80, 75, np.nan, 75], 
          "Mark3": [np.nan, 85, 98, 93], 
          "Mark4": [75, 95, np.nan, 80], 
          "Mark5": [85, 90, 95, np.nan]
          }
MyDataFrame = pd.DataFrame(MyDict)
print(MyDataFrame)
# METHOD 1 of filling missing values
MyDataFrame.fillna(100)
# METHOD 2 of filling missing values
MyDataFrame.replace(to_replace = np.nan, value = 100)

  Class  Mark1  Mark2  Mark3  Mark4  Mark5   Name Section
0     I   90.0   80.0    NaN   75.0   85.0    Ken       A
1    II    NaN   75.0   85.0   95.0   90.0  Stone       B
2     I   95.0    NaN   98.0    NaN   95.0    Tim       A
3   III   85.0   75.0   93.0   80.0    NaN  Keith       B


Class  Mark1  Mark2  Mark3  Mark4  Mark5   Name Section
0     I   90.0   80.0  100.0   75.0   85.0    Ken       A
1    II  100.0   75.0   85.0   95.0   90.0  Stone       B
2     I   95.0  100.0   98.0  100.0   95.0    Tim       A
3   III   85.0   75.0   93.0   80.0  100.0  Keith       B

In [50]:
# Question 12

# METHOD 1 - Dropping all the rows with NULL values
MyDictionary = { 'Batsman 1': [90, 20, np.nan, 86, 50],
                 'Batsman 2': [98, 60, 100, 75, 90],
                 'Batsman 3': [np.nan, np.nan, 50, 201, 90 ],
                 'Batsman 4': [40, 50, 20, 10, np.nan ]   
                }
ScoresDataFrame = pd.DataFrame(MyDictionary)
ScoresDataFrame.dropna()

# METHOD 2 - Dropping all the rows with all NULL values 
MyDictionary = { 'Batsman 1': [90, 20, np.nan, 86, 50],
                 'Batsman 2': [98, 60, np.nan, 75, 90],
                 'Batsman 3': [100, np.nan, np.nan, 201, 90 ],
                 'Batsman 4': [40, 50, np.nan, 10, np.nan ]   
                }
ScoresDataFrame = pd.DataFrame(MyDictionary)
ScoresDataFrame.dropna(how = 'all')

# METHOD 3 - Dropping all the rows with NULL values in a particular axis 
MyDictionary = { 'Batsman 1': [90, 20, np.nan, 86, 50],
                 'Batsman 2': [98, 60, 45, 75, 90],
                 'Batsman 3': [100, 50, 76, 201, 90 ],
                 'Batsman 4': [40, 50, np.nan, 10, np.nan ]   
                }
ScoresDataFrame = pd.DataFrame(MyDictionary)
ScoresDataFrame.dropna(axis = 0, how = 'any')

Batsman 1  Batsman 2  Batsman 3  Batsman 4
0       90.0         98        100       40.0
1       20.0         60         50       50.0
3       86.0         75        201       10.0

In [77]:
# Question 13
Dictionary = {'Age': [25, 30, 45, 35, 33, 35, 25, 52, 21, 24, 48, 22, 27, 28, 21, 51, 23],
 'Hair Colour': ['Black', 'Black', 'Red', 'Blond', 'Brown', 'Brown', 'Black', 'Brown', 'Blond', 'Blond', 'Black', 'Black',
                 'Brown', 'Black', 'Blond', 'Black', 'Brown'],
 'US Region': ['Southwest', 'Northwest', 'Northeast', 'Southwest', 'Southwest', 'Northeast', 'Southwest', 'Southeast', 'Southwest',
               'Northeast', 'Southwest', 'Southwest', 'Northeast', 'Southeast', 'Southeast', 'Northwest', 'Southeast'],
 'Validation': [1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1]
}
NewDataFrame = pd.DataFrame(Dictionary)
NewDataFrame.groupby(['US Region'])['Age'].mean()
NewDataFrame.groupby(['Hair Colour'])['Age','Validation'].sum().reset_index()
NewDataFrame.groupby(['US Region'])['Age'].median()

US Region
Northeast    31.0
Northwest    40.5
Southeast    25.5
Southwest    25.0
Name: Age, dtype: float64

In [63]:
# Question 14
Dictionary1 = {'Age': [25, 30, 45, 35, 33, 35, 25, 52],
 'Hair Colour': ['Black', 'Black', 'Red', 'Blond', 'Brown', 'Brown', 'Black', 'Brown'],
 'US Region': ['Southwest', 'Northwest', 'Northeast', 'Southwest', 'Southwest', 'Northeast', 'Southwest', 'Southeast'],
 'Validation': [1, 1, 1, 0, 0, 0, 0, 0]
}
Dictionary2 = {'Age': [21, 24, 48, 22, 27, 28, 21, 51, 23],
 'Hair Colour': ['Blond', 'Blond', 'Black', 'Black', 'Brown', 'Black', 'Blond', 'Black', 'Brown'],
 'US Region': ['Southwest', 'Northeast', 'Southwest', 'Southwest', 'Northeast', 'Southeast', 'Southeast', 'Northwest', 'Southeast'],
 'Validation': [1, 0, 1, 0, 0, 1, 1, 0, 1]
}
DataFrame1 = pd.DataFrame(Dictionary1)
DataFrame2 = pd.DataFrame(Dictionary2)
df = DataFrame1.merge(DataFrame2,how='right')
print(df)
df = DataFrame1.merge(DataFrame2,how='left')
print(df)
df = DataFrame1.merge(DataFrame2,how='inner')
print(df)

   Age Hair Colour  US Region  Validation
0   21       Blond  Southwest           1
1   24       Blond  Northeast           0
2   48       Black  Southwest           1
3   22       Black  Southwest           0
4   27       Brown  Northeast           0
5   28       Black  Southeast           1
6   21       Blond  Southeast           1
7   51       Black  Northwest           0
8   23       Brown  Southeast           1
   Age Hair Colour  US Region  Validation
0   25       Black  Southwest           1
1   30       Black  Northwest           1
2   45         Red  Northeast           1
3   35       Blond  Southwest           0
4   33       Brown  Southwest           0
5   35       Brown  Northeast           0
6   25       Black  Southwest           0
7   52       Brown  Southeast           0
Empty DataFrame
Columns: [Age, Hair Colour, US Region, Validation]
Index: []


In [60]:
# Question 15
Dictionary1 = {'Age': [25, 30, 45, 35, 33, 35, 25, 52],
 'Hair Colour': ['Black', 'Black', 'Red', 'Blond', 'Brown', 'Brown', 'Black', 'Brown'],
 'US Region': ['Southwest', 'Northwest', 'Northeast', 'Southwest', 'Southwest', 'Northeast', 'Southwest', 'Southeast'],
 'Validation': [1, 1, 1, 0, 0, 0, 0, 0]
}
Dictionary2 = {'Age': [21, 24, 48, 22, 27, 28, 21, 51, 23],
 'Hair Colour': ['Blond', 'Blond', 'Black', 'Black', 'Brown', 'Black', 'Blond', 'Black', 'Brown'],
 'US Region': ['Southwest', 'Northeast', 'Southwest', 'Southwest', 'Northeast', 'Southeast', 'Southeast', 'Northwest', 'Southeast'],
 'Validation': [1, 0, 1, 0, 0, 1, 1, 0, 1]
}
DataFrame1 = pd.DataFrame(Dictionary1)
DataFrame2 = pd.DataFrame(Dictionary2)
NewDataFrame = pd.concat([DataFrame1, DataFrame2],axis=0)
print(NewDataFrame)
NewDataFrame = pd.concat([DataFrame1, DataFrame2],axis=1)
print(NewDataFrame)

   Age Hair Colour  US Region  Validation
0   25       Black  Southwest           1
1   30       Black  Northwest           1
2   45         Red  Northeast           1
3   35       Blond  Southwest           0
4   33       Brown  Southwest           0
5   35       Brown  Northeast           0
6   25       Black  Southwest           0
7   52       Brown  Southeast           0
0   21       Blond  Southwest           1
1   24       Blond  Northeast           0
2   48       Black  Southwest           1
3   22       Black  Southwest           0
4   27       Brown  Northeast           0
5   28       Black  Southeast           1
6   21       Blond  Southeast           1
7   51       Black  Northwest           0
8   23       Brown  Southeast           1
    Age Hair Colour  US Region  Validation  Age Hair Colour  US Region  \
0  25.0       Black  Southwest         1.0   21       Blond  Southwest   
1  30.0       Black  Northwest         1.0   24       Blond  Northeast   
2  45.0         Red  N